### ISSUE TITLE
Support for Sonic Forces. 

### ISSUE THREAD

**Issue by KenzieMac130** [DarioSamo/libgens-sonicglvl#11]
File this under a long term goal. 
Okay, I understand this is not a simple task but I think this tool has the most potential to be used for Sonic Forces (since essentially it runs on an upgraded hedgehog engine), might require an entirely new branch.

From what I can tell the lighting system in forces has been overhauled, so the editors implimentation of GIA might need a bit of a rewrite.

Thank you.

**Comment by thesupersonic16** [comment]
https://github.com/blueskythlikesclouds/libgens-sonicglvl

**Comment by DarioSamo** [comment]
Support for Sonic Forces would likely be a new library entirely to keep HE1 and HE2 support separate. (Or a new library that is backwards compatible)

I would not be opposed to Skyth's changes being merged into this branch as long as they don't break HE1 support tho. Just needs to be reviewed first.
