### ISSUE TITLE
Sometimes, pacpack doesn't give .model or .material files

### ISSUE THREAD

**Issue by VideoGamePlayer7** [DarioSamo/libgens-sonicglvl#17]
So, this is a big issue. When I use a .pac file on pacpack, the .hkx files appear in the output folder, but sometimes, the .model and .material files do not appear. Can anyone help?

**Comment by blueskythlikesclouds** [comment]
Are you extracting the DLC .pac files?
If so, try extracting the split files (.pac.##) separately.

**Comment by VideoGamePlayer7** [comment]
Thanks for the help. Closing.
