### ISSUE TITLE
Cannot compile SonicGlvl-multi

### ISSUE THREAD

**Issue by crash5band** [DarioSamo/libgens-sonicglvl#23]
Project fails to compile with the following errors
![image](https://user-images.githubusercontent.com/44091782/71582766-42e70c80-2b14-11ea-8b49-8e54f941751d.png)

**Comment by DarioSamo** [comment]
"ui_EditorWindow.h" is an auto-generated file by Qt by using uic.exe (depends/qt/bin) on "EditorWindow.ui". The file should already be included in the project tree with a custom build event that does this, so I'm confused as to why it's missing.

Try right clicking on it and hit compile on EditorWindow.ui and see if it says anything of interest in the console output?

![image](https://user-images.githubusercontent.com/538504/71583336-c4c33f80-2aec-11ea-8038-7a1795b7f4d3.png)

**Comment by crash5band** [comment]
the error doesn't show up if the file is not open in the code editor but the cmd.exe error persists

**Comment by DarioSamo** [comment]
Could you copy the contents of the output window instead? There's not enough information in the error list I'm afraid.

**Comment by crash5band** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"cmd.exe" exited with code 1.	SonicGLvl-multi	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets	151

**Comment by crash5band** [comment]
1>------ Rebuild All started: Project: LibGens-externals, Configuration: Release Win32 ------
1>half.cpp
1>half\half.cpp(73): warning C4146: unary minus operator applied to unsigned type, result still unsigned
1>sha1.cpp
1>tinystr.cpp
1>tinyxml.cpp
1>tinyxmlerror.cpp
1>tinyxmlparser.cpp
1>connectivity_graph.cpp
1>policy.cpp
1>tri_stripper.cpp
1>LibGens-externals.vcxproj -> C:\Data\Modding Tools\sonic\libgens-sonicglvl-master\src\LibGens-externals\../../lib/Release/LibGens-externals.lib
1>Done building project "LibGens-externals.vcxproj".
2>------ Rebuild All started: Project: LibGens, Configuration: Release Win32 ------
2>stdafx.cpp
2>Animation.cpp
2>AnimationSet.cpp
2>AR.cpp
2>ArchiveTree.cpp
2>Bitmap.cpp
2>BIXF.cpp
2>Bone.cpp
2>Endian.cpp
2>Error.cpp
2>FBX.cpp
2>FBXExport.cpp
2>FBXManager.cpp
2>File.cpp
2>Ghost.cpp
2>GhostNode.cpp
2>GITextureGroup.cpp
2>Havok.cpp
2>Havok.cpp(37): warning C4005: 'HK_CLASSES_FILE' : macro redefinition
2>        C:\Data\Modding Tools\sonic\libgens-sonicglvl-master\depends\hk2010_2_0_r1\Source\Common/Base/Config/hkProductFeatures.cxx(124) : see previous definition of 'HK_CLASSES_FILE'
2>HavokAnimationCache.cpp
2>HavokEnviroment.cpp
2>HavokPhysicsCache.cpp
2>Compiling...
2>HavokPropertyDatabase.cpp
2>HavokSkeletonCache.cpp
2>InstanceMTI.cpp
2>Keyframe.cpp
2>KeyframeSet.cpp
2>Level.cpp
2>LibGens.cpp
2>Light.cpp
2>LightField.cpp
2>LostWorldObjectSet.cpp
2>LostWorldObjectSet.cpp(79): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(93): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(104): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(110): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(121): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(201): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(251): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(262): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(279): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(315): warning C4018: '<' : signed/unsigned mismatch
2>LostWorldObjectSet.cpp(359): warning C4018: '<' : signed/unsigned mismatch
2>Material.cpp
2>MaterialLibrary.cpp
2>MathGens.cpp
2>Mesh.cpp
2>Mesh.cpp(43): warning C4018: '<' : signed/unsigned mismatch
2>Model.cpp
2>ModelLibrary.cpp
2>Object.cpp
2>Object.cpp(170): warning C4018: '<' : signed/unsigned mismatch
2>Object.cpp(1500): warning C4018: '<' : signed/unsigned mismatch
2>Object.cpp(1659): warning C4018: '<' : signed/unsigned mismatch
2>Object.cpp(1669): warning C4018: '<' : signed/unsigned mismatch
2>ObjectCategory.cpp
2>ObjectElement.cpp
2>ObjectExtra.cpp
2>Compiling...
2>ObjectLibrary.cpp
2>ObjectProduction.cpp
2>ObjectSet.cpp
2>PAC.cpp
2>Parameter.cpp
2>Path.cpp
2>Shader.cpp
2>StringTable.cpp
2>Submesh.cpp
2>Tags.cpp
2>Terrain.cpp
2>TerrainBlock.cpp
2>TerrainGroup.cpp
2>TerrainInstance.cpp
2>Texture.cpp
2>UVAnimation.cpp
2>UVAnimationLibrary.cpp
2>UVAnimationSet.cpp
2>Vertex.cpp
2>VertexFormat.cpp
2>Compiling...
2>VRMap.cpp
2>LibGens.vcxproj -> C:\Data\Modding Tools\sonic\libgens-sonicglvl-master\src\LibGens\../../lib/Release/LibGens.lib
2>Done building project "LibGens.vcxproj".
3>------ Rebuild All started: Project: SonicGLvl-multi, Configuration: Release Win32 ------
3>MOC EditorTerrainStreamer.h
3>moc: Too many input files specified: 'C:\Data\Modding' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\EditorTerrainStreamer.h' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\moc_EditorTerrainStreamer.cpp'
3>Usage: ..\..\depends\qt\bin\moc.exe [options] [header-file] [@option-file]
3>Qt Meta Object Compiler version 67 (Qt 5.5.0)
3>
3>Options:
3>  -?, -h, --help           Displays this help.
3>  -v, --version            Displays version information.
3>  -o <file>                Write output to file rather than stdout.
3>  -I <dir>                 Add dir to the include path for header files.
3>  -F <framework>           Add Mac framework to the include path for header
3>                           files.
3>  -E                       Preprocess only; do not generate meta object code.
3>  -D <macro[=def]>         Define macro, with optional definition.
3>  -U <macro>               Undefine macro.
3>  -M <key=value>           Add key/value pair to plugin meta data
3>  -i                       Do not generate an #include statement.
3>  -p <path>                Path prefix for included file.
3>  -f <file>                Force #include <file> (overwrite default).
3>  -b <file>                Prepend #include <file> (preserve default include).
3>  -n <which>               Do not display notes (-nn) or warnings (-nw).
3>                           Compatibility option.
3>  --no-notes               Do not display notes.
3>  --no-warnings            Do not display warnings (implies --no-notes).
3>  --ignore-option-clashes  Ignore all options that conflict with compilers,
3>                           like -pthread conflicting with moc's -p option.
3>
3>Arguments:
3>  [header-file]            Header file to read from, otherwise stdin.
3>  [@option-file]           Read additional options from option-file.
3>MOC EditorViewport.h
3>moc: Too many input files specified: 'C:\Data\Modding' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\EditorViewport.h' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\moc_EditorViewport.cpp'
3>Usage: ..\..\depends\qt\bin\moc.exe [options] [header-file] [@option-file]
3>Qt Meta Object Compiler version 67 (Qt 5.5.0)
3>
3>Options:
3>  -?, -h, --help           Displays this help.
3>  -v, --version            Displays version information.
3>  -o <file>                Write output to file rather than stdout.
3>  -I <dir>                 Add dir to the include path for header files.
3>  -F <framework>           Add Mac framework to the include path for header
3>                           files.
3>  -E                       Preprocess only; do not generate meta object code.
3>  -D <macro[=def]>         Define macro, with optional definition.
3>  -U <macro>               Undefine macro.
3>  -M <key=value>           Add key/value pair to plugin meta data
3>  -i                       Do not generate an #include statement.
3>  -p <path>                Path prefix for included file.
3>  -f <file>                Force #include <file> (overwrite default).
3>  -b <file>                Prepend #include <file> (preserve default include).
3>  -n <which>               Do not display notes (-nn) or warnings (-nw).
3>                           Compatibility option.
3>  --no-notes               Do not display notes.
3>  --no-warnings            Do not display warnings (implies --no-notes).
3>  --ignore-option-clashes  Ignore all options that conflict with compilers,
3>                           like -pthread conflicting with moc's -p option.
3>
3>Arguments:
3>  [header-file]            Header file to read from, otherwise stdin.
3>  [@option-file]           Read additional options from option-file.
3>MOC EditorViewportsWidget.h
3>Usage: ..\..\depends\qt\bin\moc.exe [options] [header-file] [@option-file]
3>Qt Meta Object Compiler version 67 (Qt 5.5.0)
3>
3>Options:
3>  -?, -h, --help           Displays this help.
3>  -v, --version            Displays version information.
3>  -o <file>                Write output to file rather than stdout.
3>  -I <dir>                 Add dir to the include path for header files.
3>  -F <framework>           Add Mac framework to the include path for header
3>                           files.
3>  -E                       Preprocess only; do not generate meta object code.
3>  -D <macro[=def]>         Define macro, with optional definition.
3>  -U <macro>               Undefine macro.
3>  -M <key=value>           Add key/value pair to plugin meta data
3>  -i                       Do not generate an #include statement.
3>  -p <path>                Path prefix for included file.
3>  -f <file>                Force #include <file> (overwrite default).
3>  -b <file>                Prepend #include <file> (preserve default include).
3>  -n <which>               Do not display notes (-nn) or warnings (-nw).
3>                           Compatibility option.
3>  --no-notes               Do not display notes.
3>  --no-warnings            Do not display warnings (implies --no-notes).
3>  --ignore-option-clashes  Ignore all options that conflict with compilers,
3>                           like -pthread conflicting with moc's -p option.
3>
3>Arguments:
3>  [header-file]            Header file to read from, otherwise stdin.
3>  [@option-file]           Read additional options from option-file.
3>moc: Too many input files specified: 'C:\Data\Modding' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\EditorViewportsWidget.h' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\moc_EditorViewportsWidget.cpp'
3>MOC EditorWindow.h
3>moc: Too many input files specified: 'C:\Data\Modding' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\EditorWindow.h' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\moc_EditorWindow.cpp'
3>Usage: ..\..\depends\qt\bin\moc.exe [options] [header-file] [@option-file]
3>Qt Meta Object Compiler version 67 (Qt 5.5.0)
3>
3>Options:
3>  -?, -h, --help           Displays this help.
3>  -v, --version            Displays version information.
3>  -o <file>                Write output to file rather than stdout.
3>  -I <dir>                 Add dir to the include path for header files.
3>  -F <framework>           Add Mac framework to the include path for header
3>                           files.
3>  -E                       Preprocess only; do not generate meta object code.
3>  -D <macro[=def]>         Define macro, with optional definition.
3>  -U <macro>               Undefine macro.
3>  -M <key=value>           Add key/value pair to plugin meta data
3>  -i                       Do not generate an #include statement.
3>  -p <path>                Path prefix for included file.
3>  -f <file>                Force #include <file> (overwrite default).
3>  -b <file>                Prepend #include <file> (preserve default include).
3>  -n <which>               Do not display notes (-nn) or warnings (-nw).
3>                           Compatibility option.
3>  --no-notes               Do not display notes.
3>  --no-warnings            Do not display warnings (implies --no-notes).
3>  --ignore-option-clashes  Ignore all options that conflict with compilers,
3>                           like -pthread conflicting with moc's -p option.
3>
3>Arguments:
3>  [header-file]            Header file to read from, otherwise stdin.
3>  [@option-file]           Read additional options from option-file.
3>MOC OgreViewportWidget.h
3>moc: Too many input files specified: 'C:\Data\Modding' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\OgreViewportWidget.h' 'Tools\sonic\libgens-sonicglvl-master\src\SonicGLvl-multi\moc_OgreViewportWidget.cpp'
3>Usage: ..\..\depends\qt\bin\moc.exe [options] [header-file] [@option-file]
3>Qt Meta Object Compiler version 67 (Qt 5.5.0)
3>
3>Options:
3>  -?, -h, --help           Displays this help.
3>  -v, --version            Displays version information.
3>  -o <file>                Write output to file rather than stdout.
3>  -I <dir>                 Add dir to the include path for header files.
3>  -F <framework>           Add Mac framework to the include path for header
3>                           files.
3>  -E                       Preprocess only; do not generate meta object code.
3>  -D <macro[=def]>         Define macro, with optional definition.
3>  -U <macro>               Undefine macro.
3>  -M <key=value>           Add key/value pair to plugin meta data
3>  -i                       Do not generate an #include statement.
3>  -p <path>                Path prefix for included file.
3>  -f <file>                Force #include <file> (overwrite default).
3>  -b <file>                Prepend #include <file> (preserve default include).
3>  -n <which>               Do not display notes (-nn) or warnings (-nw).
3>                           Compatibility option.
3>  --no-notes               Do not display notes.
3>  --no-warnings            Do not display warnings (implies --no-notes).
3>  --ignore-option-clashes  Ignore all options that conflict with compilers,
3>                           like -pthread conflicting with moc's -p option.
3>
3>Arguments:
3>  [header-file]            Header file to read from, otherwise stdin.
3>  [@option-file]           Read additional options from option-file.
3>UIC EditorWindow.ui
3>uic: Error in line 1, column 0 : Premature end of document.
3>File 'C:\Data\Modding' is not valid
3>RCC EditorResource.qrc
3>..\..\depends\qt\bin\rcc.exe: File does not exist 'C:\Data\Modding'
3>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 1.
3>Done building project "SonicGLvl-multi.vcxproj" -- FAILED.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

**Comment by DarioSamo** [comment]
Oh, I think it's caused by the spaces in the path. It seems the custom build tool commands are missing the " on the arguments.

Either move the build directory to somewhere without spaces or you'll have to fix the custom build tools for every file that calls either moc, uic, or rcc.

**Comment by crash5band** [comment]
oh that did it. Thanks for the help!
