### ISSUE TITLE
https://software.intel.com/sites/havok/en/ is no longer available.

### ISSUE THREAD

**Issue by Voxel-Studios** [DarioSamo/libgens-sonicglvl#3]
Hello,

I have noticed that the Havok 2010 distribution can no longer be downloaded from the official website. (https://software.intel.com/sites/havok/en/)

Can you possibly re-upload this to another site? I understand that it's a SonicGlvl dependent, and I, myself, currently need it.

Many thanks,
-Voxel Studios

**Comment by DarioSamo** [comment]
http://pastebin.com/dqR4vR5x

**Comment by Voxel-Studios** [comment]
Ah, yes. Haha, sorry; I didn't see that. >_<
