### ISSUE TITLE
Having Trouble With Hedgehog Converter.

### ISSUE THREAD

**Issue by sajeed3** [DarioSamo/libgens-sonicglvl#6]
https://drive.google.com/file/d/0B_FrK3HBgpjbcml1NVhINnh5ZUU/view?usp=sharing
When i convert this model hedgehog converter crashes .

**Comment by slashiee** [comment]
Double check the materials being used on the objects. I'm assuming you used SALVL for this? It's not the most accurate program out there.

Example: https://youtu.be/oB1ZYNp9bEc?t=130
