### ISSUE TITLE
ModelFBX - Animation Files are all corrupted

### ISSUE THREAD

**Issue by Morphexe** [DarioSamo/libgens-sonicglvl#7]
I am trying to use your ModelFBX, but the exported animations are all corrupted, and I missing something?

Is there another way to export the fbx animations?

**Comment by DarioSamo** [comment]
Where are you importing them? What version?

**Comment by Morphexe** [comment]
I tried to import them in 3DS Max, belive it or not I just made it work, the Up Axis was not correct it seems on my original model. So I guess this was my bad, although I have been attempting do export the animations for a few days.

(Although when importing the FBX animations in 3DS I get a ton of weird lines, if the mesh has the correct Up Axis it animates correctly none the less). 

Sorry for the dumb issue then, and props for the quick reply!

**Comment by DarioSamo** [comment]
Do you mean the large bounding boxes? That's an issue on the 3DS Max importer. You can try importing as bones and see if that makes it behave any better. (It's on the import options from the file menu)
